### ISSUE TITLE
histogram_equalisation method does not recover from IOError

### ISSUE THREAD

**Issue by gauthiermartin** [mdbloice/Augmentor#72]
While using histogram_equalisation method i got multiple error that go raised  by PIL.

Here is the error returned by my terminal

Processing 000010.jpg:  81%|███████████████████████████████████████████████████████████████████████████████████████████████████▋                       | 342/422 [00:29<00:06, 12.99 Samples/s]Output directory set to /home/spark/Desktop/Augmentation/images/Pont Jacques-Cartier/_histogram_equalisation.Traceback (most recent call last):
  File "core/main.py", line 43, in <module>
    main = Main()
  File "core/main.py", line 10, in __init__
    self.main()
  File "core/main.py", line 40, in main
    augmentator.execute_all_single_image_augmentation()
  File "/home/spark/Projects/image-augmentation-tool/core/augmentator.py", line 457, in execute_all_single_image_augmentation
    self._histogram_equalisation()
  File "/home/spark/Projects/image-augmentation-tool/core/augmentator.py", line 229, in _histogram_equalisation
    pipeline.sample(count)
  File "/home/spark/.virtualenvs/image-augmentation-tool/lib/python3.6/site-packages/Augmentor/Pipeline.py", line 254, in sample
    self._execute(augmentor_image)
  File "/home/spark/.virtualenvs/image-augmentation-tool/lib/python3.6/site-packages/Augmentor/Pipeline.py", line 192, in _execute
    image = operation.perform_operation(image)
  File "/home/spark/.virtualenvs/image-augmentation-tool/lib/python3.6/site-packages/Augmentor/Operations.py", line 123, in perform_operation
    return ImageOps.equalize(image)
  File "/home/spark/.virtualenvs/image-augmentation-tool/lib/python3.6/site-packages/PIL/ImageOps.py", line 248, in equalize
    return _lut(image, lut)
  File "/home/spark/.virtualenvs/image-augmentation-tool/lib/python3.6/site-packages/PIL/ImageOps.py", line 57, in _lut
    raise IOError("not supported for this image mode")
OSError: not supported for this image mode

**Comment by mdbloice** [comment]
Hi. I am not exactly sure what this is, but I'd imagine it's because some of your images are binary/1-bit perhaps?
