### ISSUE TITLE
Unable to save out images after augmenting

### ISSUE THREAD

**Issue by ssundar6087** [mdbloice/Augmentor#82]
Hello,

I installed Augmentor successfully using pip. After that I was able to write a short script to augment images and ran it without any issue.

Today, when I tried to run the script on a different set of images, I got the error : 
Error writing f8aee8ea-418c-4742-a977-5896b2b160d5, .
Change save_format to PNG?
You can change the save format using the set_save_format(save_format) function.

I tried using set_save_format("auto") and the problem still persists. Can you please help?

**Comment by mdbloice** [comment]
Hi @ssundar6087, sure let's try to fix the problem. This has something to do with how Augmentor and PIL handle saving images of different formats. Do your original files have file endings? I suppose they must if they were added to the pipeline in the first place... could you tell me the file types of the images you are trying to augment? Are they PNG with an alpha channel? Or are they JPEGs? 

Thanks, M.

**Comment by mdbloice** [comment]
Also, are you maybe initialising the pipeline using the `save_format` parameter like so:
```python
p = Augmentor.Pipeline("/tmp/images/", save_format="BMP") 
```
or something similar? 

If you force a format using `save_format`, then you may get errors when augmenting images that cannot be saved in this format. For example when trying to save PNG images with an alpha channel as a JPEG image. Augmentor will not coerce these into a format that it can save.

**Comment by ssundar6087** [comment]
@mdbloice : thanks for the quick response
Here is the snippet of code I am using
`import Augmentor`
`p = Augmentor.Pipeline("/data/sairam/test_aug/")`
`p.ground_truth("/data/sairam/test_aug/ground_truth")`
`p.rotate(probability = 1, max_left_rotation =5, max_right_rotation =5)`
`p.flip_left_right(probability = 0.5)`
`p.flip_top_bottom(probability = 0.3)`
`p.sample(10)`

The input format is .jpg . When I first installed augmentor the day before, I was able to run this script with no trouble. When I tried yesterday and today, it seems to give the error message above.
To this script, i then added 
`p.set_save_format(save_format="auto")`
to see if the error goes away, but it doesn't.

**Comment by abrad1212** [comment]
@mdbloice This is happening to me as well.
Files are in jpg format

**Comment by mdbloice** [comment]
Ok, it is rather strange as this works on my end. Another question: are the ground truth images are also in the same format?

**Comment by ssundar6087** [comment]
@mdbloice the ground truth images are also .jpg and have the same names as the input files (per the readme.md)

What's weird is that it worked properly for the same set of images the first time. I then selected a subset of these images to augment differently, and that's when this happened.

**Comment by mdbloice** [comment]
@ssundar6087 Ok, well what is also strange is that your error message contains no text. Normally you'd get something about why the image failed to save, but the error `Error writing f8aee8ea-418c-4742-a977-5896b2b160d5, .` makes little sense as it does not contain the error text that is normally printed. 
Have you ruled out things like not having proper write access to the output folder? 
In the mean time I am going to add an option to the `set_save_format()` function called `coerce` which will force saving of images into a format which should allow for any file to saved, such as RGB.

**Comment by mdbloice** [comment]
Oh, and what version of Augmentor are you using? 
You can check it quickly using 
```python
import Augmentor
print(Augmentor.__version__)
```
The current version is 0.2.0.

**Comment by ssundar6087** [comment]
@mdbloice The version I'm running is also 0.2.0 

The output folder certainly has proper write access. It is the same folder to which I wrote out the first batch of augmented images. I have also tried creating a new folder and writing images out to that, but I still get the same issue. I agree that the error message is weird. In fact, it seems to resemble one of the names of the generated output images I saw in the past.
For example, if my input and ground truth pair were input1.jpg and /groundtruth/input1.jpg , the output image usually was something like f8aee8ea-418c-4742-a977-5896b2b160d5.jpg and _ground_truth_(1)_f8aee8ea-418c-4742-a977-5896b2b160d5.jpg

**Comment by mdbloice** [comment]
Ok, what does your folder structure look like? I mean the structure of the images folder relative to the ground_truth directory, and the contents of these folders. For example, are there sub-folders in the ground_truth directory? Are there sub-folders in the images directory? Is the ground_truth directory a sub-folder of the images folder by any chance? 

Thanks!

**Comment by ssundar6087** [comment]
@mdbloice The folder structure is as follows : 

Input Images
----|
      |
      ground_truth_images

The Ground Image folder is a sub folder of the input image folder. There are no other sub folders within both the ground truth and input image folder.

Is that an incorrect usage of the package?

**Comment by ssundar6087** [comment]
Quick update : when I moved the ground_truth folder out of the input_images folder, the script works without an issue.

**Comment by mdbloice** [comment]
@ssundar6087, thanks for letting me know, I will fix that bug ASAP. I suppose my tests didn't pick up that scenario, but I am pleased there is a workaround for now at least. 
M.

**Comment by ArthurSav** [comment]
I assume this is not fixed yet, using **v0.2.2.**

Folder structure: `data/characters01` (No other files/folders in `data` except for character01)

If i set the root folder as **data**, i get an error:

`p = Augmentor.Pipeline("data", save_format='png')`
`Initialised with 20 image(s) found.
Output directory set to data/output.`
...
`Error writing 46848e76-74a3-413d-ae84-e5f59c5dde89, . Change save_format to PNG?`

Like mentioned above, If i set the root folder as **data/character01**, it works:

`p = Augmentor.Pipeline("data/character01", save_format='png')`.

Is this intended?

**Comment by mdbloice** [comment]
Hi @ArthurSav yeah if you have 1 class then it is best to initialise in a directory that contains only the images for that class. If you have multiple classes then initialise within a directory that contains sub-directories, one directory for each class.

**Comment by MoKhaleel** [comment]
I have a problem with the code works for some directories and throw and error for the others.

folders =  ['C:/.../datasets/images_test_cropped/042.Vermilion_Flycatcher', 'C:/.../datasets/images_test_cropped/043.Yellow_bellied_Flycatcher', ...]

target_folders = ['C:/.../datasets/images_test_cropped_augmented/042.Vermilion_Flycatcher', 'C:/.../datasets/images_test_cropped_augmented/043.Yellow_bellied_Flycatcher', ...]


`for i in range(len(folders)):
    fd = folders[i]
    tfd = target_folders[i]

    # rotation
    p = Augmentor.Pipeline(source_directory=fd, output_directory=tfd)
    p.rotate(probability=1, max_left_rotation=15, max_right_rotation=15)
    p.flip_left_right(probability=0.5)
    for _ in range(10):
        p.process()
    del p`


Error Message:
Traceback (most recent call last):
  File "C:\Users\...\Anaconda3\envs\tensorflow_gpuenv\lib\site-packages\Augmentor\Pipeline.py", line 251, in _execute
    images[i].save(os.path.join(augmentor_image.output_directory, save_name))
  File "C:\Users\...\Anaconda3\envs\tensorflow_gpuenv\lib\site-packages\PIL\Image.py", line 2099, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\...\\datasets\\images_test_cropped_augmented\\043.Yellow_bellied_Flycatcher\\043.Yellow_bellied_Flycatcher_original_Yellow_Bellied_Flycatcher_0001_795488.jpg_1c2558a1-5704-4f6d-a7e1-a0a1da39efe3.jpg'

P.S. The file is not yet created on the disk maybe that's why this error triggered. But idk why the code is trying to read a file from the dist that does not exist yet.

**Comment by anaghajoshi111** [comment]
> I have a problem with the code works for some directories and throw and error for the others.
> 
> folders = ['C:/.../datasets/images_test_cropped/042.Vermilion_Flycatcher', 'C:/.../datasets/images_test_cropped/043.Yellow_bellied_Flycatcher', ...]
> 
> target_folders = ['C:/.../datasets/images_test_cropped_augmented/042.Vermilion_Flycatcher', 'C:/.../datasets/images_test_cropped_augmented/043.Yellow_bellied_Flycatcher', ...]
> 
> `for i in range(len(folders)):
> fd = folders[i]
> tfd = target_folders[i]
> 
> ```
> # rotation
> p = Augmentor.Pipeline(source_directory=fd, output_directory=tfd)
> p.rotate(probability=1, max_left_rotation=15, max_right_rotation=15)
> p.flip_left_right(probability=0.5)
> for _ in range(10):
>     p.process()
> del p`
> ```
> 
> Error Message:
> Traceback (most recent call last):
> File "C:\Users...\Anaconda3\envs\tensorflow_gpuenv\lib\site-packages\Augmentor\Pipeline.py", line 251, in _execute
> images[i].save(os.path.join(augmentor_image.output_directory, save_name))
> File "C:\Users...\Anaconda3\envs\tensorflow_gpuenv\lib\site-packages\PIL\Image.py", line 2099, in save
> fp = builtins.open(filename, "w+b")
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\...\datasets\images_test_cropped_augmented\043.Yellow_bellied_Flycatcher\043.Yellow_bellied_Flycatcher_original_Yellow_Bellied_Flycatcher_0001_795488.jpg_1c2558a1-5704-4f6d-a7e1-a0a1da39efe3.jpg'
> 
> P.S. The file is not yet created on the disk maybe that's why this error triggered. But idk why the code is trying to read a file from the dist that does not exist yet.

I'm facing the exact issue. Did you happen to find a workaround yet?

**Comment by AmrishaVohra** [comment]
The issue seems to be with the path length. I reduced the path length by changing the folder name, and it worked

**Comment by kunal449** [comment]
> > I have a problem with the code works for some directories and throw and error for the others.
> > folders = ['C:/.../datasets/images_test_cropped/042.Vermilion_Flycatcher', 'C:/.../datasets/images_test_cropped/043.Yellow_bellied_Flycatcher', ...]
> > target_folders = ['C:/.../datasets/images_test_cropped_augmented/042.Vermilion_Flycatcher', 'C:/.../datasets/images_test_cropped_augmented/043.Yellow_bellied_Flycatcher', ...]
> > `for i in range(len(folders)):
> > fd = folders[i]
> > tfd = target_folders[i]
> > ```
> > # rotation
> > p = Augmentor.Pipeline(source_directory=fd, output_directory=tfd)
> > p.rotate(probability=1, max_left_rotation=15, max_right_rotation=15)
> > p.flip_left_right(probability=0.5)
> > for _ in range(10):
> >     p.process()
> > del p`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Error Message:
> > Traceback (most recent call last):
> > File "C:\Users...\Anaconda3\envs\tensorflow_gpuenv\lib\site-packages\Augmentor\Pipeline.py", line 251, in _execute
> > images[i].save(os.path.join(augmentor_image.output_directory, save_name))
> > File "C:\Users...\Anaconda3\envs\tensorflow_gpuenv\lib\site-packages\PIL\Image.py", line 2099, in save
> > fp = builtins.open(filename, "w+b")
> > FileNotFoundError: [Errno 2] No such file or directory: 'C:...\datasets\images_test_cropped_augmented\043.Yellow_bellied_Flycatcher\043.Yellow_bellied_Flycatcher_original_Yellow_Bellied_Flycatcher_0001_795488.jpg_1c2558a1-5704-4f6d-a7e1-a0a1da39efe3.jpg'
> > P.S. The file is not yet created on the disk maybe that's why this error triggered. But idk why the code is trying to read a file from the dist that does not exist yet.
> 
> I'm facing the exact issue. Did you happen to find a workaround yet?

Faced the same issue on Windows 11, and reducing the absolute path length worked like charm

**Comment by pkrbansal** [comment]
Found the solution: change the long path variable setting from the registry key. change the value from 0 to 1. Follow the following link: https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/The-Windows-10-default-path-length-limitation-MAX-PATH-is-256-characters.html

Trust me. It works!!!!
