### ISSUE TITLE
Pipeline.sample_with_array, appears to requre an (n h w c) ndarray, but PIL fromarray appears to be then erroring.

### ISSUE THREAD

**Issue by gmonkman** [mdbloice/Augmentor#90]
```
import numpy as np
from Augmentor import Pipeline
p=Pipeline()
p.rotate(1, 10, 10)
img = np.ones([100,100,3], dtype='uint8')
outimg = p.sample_with_array(img)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python354x64\lib\site-packages\Augmentor\Pipeline.py", line 315, in sample_with_array
    return self._execute(a, save_to_disk)
  File "C:\Python354x64\lib\site-packages\Augmentor\Pipeline.py", line 218, in _execute
    return images[0]
IndexError: list index out of range
```

Gets a bit further by adding an extra dim, but fails in PIL due to extra axis-0;

```
img = np.ones([1,100,100,3], dtype='uint8')

Traceback (most recent call last):
  File "C:\Python354x64\lib\site-packages\PIL\Image.py", line 2423, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 100, 3), '|u1')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python354x64\lib\site-packages\Augmentor\Pipeline.py", line 313, in sample_with_array
    a.image_PIL = Image.fromarray(image_array)
  File "C:\Python354x64\lib\site-packages\PIL\Image.py", line 2426, in fromarray
    raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type
```

I hope i'm using it correctly, I just want to pass in an ndarray of type uint8, which i've done some custom preprocessing on, and get out a transformed ndarray.

**Comment by liangt** [comment]
As far as I know, this is a bug. Actually, sample_with_array accepts a single image in array-like format, so your first usage should be right. However, this is a bug in sample_with_array. sample_with_array just calls _excute, while _excute currently only supports pass image through the current pipeline, when you pass array, the result is just an empty array, so you get IndexError.

**Comment by 0x8b** [comment]
Why #98 wasn't merged? It works for me perfectly.

**Comment by nyk2001** [comment]
I am having issue and cannot make it work...

**Comment by mfruhner** [comment]
Having the same issue here!
